// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Swagger - Uso e integracion de la API de Star Wars y una propia",
    "version": "1",
    "description": "Esta API permite obtener personajes de Star Wars y crear personajes propios"
  },
  "paths": {
    "/dev/api/v1/personajes": {
      "get": {
        "summary": "Obtener personajes",
        "description": "Obtiene todos los personajes de Star Wars con opción de búsqueda por nombre, la información se obtiene de un servicio externo y de la base de datos propia",
        "operationId": "api.get./dev/api/v1/personajes",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "buscar",
            "type": "string",
            "description": "Cadena a buscar por nombre",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "Operación exitosa"
          },
          "500": {
            "description": "Error en el procesamiento"
          }
        }
      },
      "post": {
        "summary": "Crear personaje",
        "description": "Se crea un personaje de Star Wars y se guarda en una base de datos propia",
        "operationId": "api.post./dev/api/v1/personajes",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Personaje"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Operación exitosa"
          },
          "500": {
            "description": "Error en el procesamiento"
          }
        }
      }
    }
  },
  "definitions": {
    "Personaje": {
      "properties": {
        "nombre": {
          "title": "Personaje.nombre",
          "type": "string"
        },
        "altura": {
          "title": "Personaje.altura",
          "type": "string"
        },
        "peso": {
          "title": "Personaje.peso",
          "type": "string"
        },
        "color_de_pelo": {
          "title": "Personaje.color_de_pelo",
          "type": "string"
        },
        "color_de_piel": {
          "title": "Personaje.color_de_piel",
          "type": "string"
        },
        "color_de_ojos": {
          "title": "Personaje.color_de_ojos",
          "type": "string"
        },
        "ano_de_nacimiento": {
          "title": "Personaje.ano_de_nacimiento",
          "type": "string"
        },
        "genero": {
          "title": "Personaje.genero",
          "type": "string"
        },
        "mundo_natal": {
          "title": "Personaje.mundo_natal",
          "type": "string"
        },
        "peliculas": {
          "items": {
            "title": "Personaje.peliculas.[]",
            "type": "string"
          },
          "title": "Personaje.peliculas",
          "type": "array"
        },
        "especies": {
          "items": {
            "title": "Personaje.especies.[]",
            "type": "string"
          },
          "title": "Personaje.especies",
          "type": "array"
        },
        "vehiculos": {
          "items": {
            "title": "Personaje.vehiculos.[]",
            "type": "string"
          },
          "title": "Personaje.vehiculos",
          "type": "array"
        },
        "naves_estelares": {
          "items": {
            "title": "Personaje.naves_estelares.[]",
            "type": "string"
          },
          "title": "Personaje.naves_estelares",
          "type": "array"
        },
        "creado": {
          "title": "Personaje.creado",
          "type": "string"
        },
        "editado": {
          "title": "Personaje.editado",
          "type": "string"
        },
        "url": {
          "title": "Personaje.url",
          "type": "string"
        }
      },
      "required": [
        "nombre",
        "altura",
        "peso",
        "color_de_pelo",
        "color_de_piel",
        "color_de_ojos",
        "ano_de_nacimiento",
        "genero",
        "mundo_natal",
        "peliculas",
        "especies",
        "vehiculos",
        "naves_estelares",
        "creado",
        "editado",
        "url"
      ],
      "additionalProperties": false,
      "title": "Personaje",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};